import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import importPlugin from 'eslint-plugin-import';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import globals from 'globals';

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat['jsx-runtime'],
  importPlugin.flatConfigs.recommended,
  jsxA11y.flatConfigs.recommended,

  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser },
    },
    settings: {
      react: { version: 'detect' },
      'import/resolver': { node: { extensions: ['.js', '.jsx', '.ts', '.tsx'] } },
    },
    rules: {
      // === Airbnb parity rules (from ESLint 8 + airbnb config) ===
      'array-callback-return': ['error', {allowImplicit: true, checkForEach: false, allowVoid: false}],
      'arrow-spacing': ['error', {before: true, after: true}],
      'block-scoped-var': 'error',
      'camelcase': ['error', {properties: 'never', ignoreDestructuring: false, ignoreImports: false, ignoreGlobals: false}],
      'class-methods-use-this': ['error', {exceptMethods: ['render', 'getInitialState', 'getDefaultProps', 'getChildContext', 'componentWillMount', 'UNSAFE_componentWillMount', 'componentDidMount', 'componentWillReceiveProps', 'UNSAFE_componentWillReceiveProps', 'shouldComponentUpdate', 'componentWillUpdate', 'UNSAFE_componentWillUpdate', 'componentDidUpdate', 'componentWillUnmount', 'componentDidCatch', 'getSnapshotBeforeUpdate'], enforceForClassFields: true}],
      'comma-style': ['error', 'last', {exceptions: {ArrayExpression: false, ArrayPattern: false, ArrowFunctionExpression: false, CallExpression: false, FunctionDeclaration: false, FunctionExpression: false, ImportDeclaration: false, ObjectExpression: false, ObjectPattern: false, VariableDeclaration: false, NewExpression: false}}],
      'computed-property-spacing': ['error', 'never'],
      'consistent-return': 'error',
      'curly': ['error', 'multi-line'],
      'default-case': ['error', {commentPattern: '^no default$'}],
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-location': ['error', 'property'],
      'dot-notation': ['error', {allowKeywords: true, allowPattern: ''}],
      'func-call-spacing': ['error', 'never'],
      'function-call-argument-newline': ['error', 'consistent'],
      'function-paren-newline': ['error', 'multiline-arguments'],
      'generator-star-spacing': ['error', {before: false, after: true}],
      'global-require': 'error',
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'implicit-arrow-linebreak': ['error', 'beside'],
      'import/first': 'error',
      'import/newline-after-import': 'error',
      'import/no-absolute-path': 'error',
      'import/no-amd': 'error',
      'import/no-cycle': ['error', {maxDepth: '∞', ignoreExternal: false, allowUnsafeDynamicCyclicDependency: false, disableScc: false}],
      'import/no-duplicates': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-extraneous-dependencies': ['error', {devDependencies: ['test/**', 'tests/**', 'spec/**', '**/__tests__/**', '**/__mocks__/**', 'test.{js,jsx}', 'test-*.{js,jsx}', '**/*{.,_}{test,spec}.{js,jsx}', '**/jest.config.js', '**/jest.setup.js', '**/vue.config.js', '**/webpack.config.js', '**/webpack.config.*.js', '**/rollup.config.js', '**/rollup.config.*.js', '**/gulpfile.js', '**/gulpfile.*.js', '**/Gruntfile{,.js}', '**/protractor.conf.js', '**/protractor.conf.*.js', '**/karma.conf.js', '**/.eslintrc.js'], optionalDependencies: false}],
      'import/no-import-module-exports': ['error', {exceptions: []}],
      'import/no-mutable-exports': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'error',
      'import/no-named-default': 'error',
      'import/no-relative-packages': 'error',
      'import/no-self-import': 'error',
      'import/no-useless-path-segments': ['error', {commonjs: true}],
      'import/no-webpack-loader-syntax': 'error',
      'import/order': ['error', {groups: [['builtin', 'external', 'internal']], distinctGroup: true, sortTypesGroup: false, named: false, warnOnUnassignedImports: false}],
      'import/prefer-default-export': 'error',
      'jsx-a11y/control-has-associated-label': ['error', {labelAttributes: ['label'], controlComponents: [], ignoreElements: ['audio', 'canvas', 'embed', 'input', 'textarea', 'tr', 'video'], ignoreRoles: ['grid', 'listbox', 'menu', 'menubar', 'radiogroup', 'row', 'tablist', 'toolbar', 'tree', 'treegrid'], depth: 5}],
      'jsx-a11y/lang': 'error',
      'linebreak-style': ['error', 'unix'],
      'lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: false}],
      'max-classes-per-file': ['error', 1],
      'max-len': ['error', 100, 2, {ignoreUrls: true, ignoreComments: false, ignoreRegExpLiterals: true, ignoreStrings: true, ignoreTemplateLiterals: true}],
      'new-cap': ['error', {newIsCap: true, newIsCapExceptions: [], capIsNew: false, capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'], properties: true}],
      'new-parens': 'error',
      'newline-per-chained-call': ['error', {ignoreChainWithDepth: 4}],
      'no-await-in-loop': 'error',
      'no-bitwise': 'error',
      'no-buffer-constructor': 'error',
      'no-caller': 'error',
      'no-confusing-arrow': ['error', {allowParens: true, onlyOneSimpleParam: false}],
      'no-constructor-return': 'error',
      'no-continue': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-floating-decimal': 'error',
      'no-implied-eval': 'error',
      'no-inner-declarations': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': ['error', {allowLoop: false, allowSwitch: false}],
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-mixed-operators': ['error', {groups: [['%', '**'], ['%', '+'], ['%', '-'], ['%', '*'], ['%', '/'], ['/', '*'], ['&', '|', '<<', '>>', '>>>'], ['==', '!=', '===', '!=='], ['&&', '||']], allowSamePrecedence: false}],
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'error',
      'no-nested-ternary': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-require': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-path-concat': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-restricted-exports': ['error', {restrictedNamedExports: ['default', 'then']}],
      'no-restricted-globals': ['error', {name: 'isFinite', message: 'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite'}, {name: 'isNaN', message: 'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan'}, 'addEventListener', 'blur', 'close', 'closed', 'confirm', 'defaultStatus', 'defaultstatus', 'event', 'external', 'find', 'focus', 'frameElement', 'frames', 'history', 'innerHeight', 'innerWidth', 'length', 'location', 'locationbar', 'menubar', 'moveBy', 'moveTo', 'name', 'onblur', 'onerror', 'onfocus', 'onload', 'onresize', 'onunload', 'open', 'opener', 'opera', 'outerHeight', 'outerWidth', 'pageXOffset', 'pageYOffset', 'parent', 'print', 'removeEventListener', 'resizeBy', 'resizeTo', 'screen', 'screenLeft', 'screenTop', 'screenX', 'screenY', 'scroll', 'scrollbars', 'scrollBy', 'scrollTo', 'scrollX', 'scrollY', 'self', 'status', 'statusbar', 'stop', 'toolbar', 'top'],
      'no-restricted-properties': ['error', {object: 'arguments', property: 'callee', message: 'arguments.callee is deprecated'}, {object: 'global', property: 'isFinite', message: 'Please use Number.isFinite instead'}, {object: 'self', property: 'isFinite', message: 'Please use Number.isFinite instead'}, {object: 'window', property: 'isFinite', message: 'Please use Number.isFinite instead'}, {object: 'global', property: 'isNaN', message: 'Please use Number.isNaN instead'}, {object: 'self', property: 'isNaN', message: 'Please use Number.isNaN instead'}, {object: 'window', property: 'isNaN', message: 'Please use Number.isNaN instead'}, {property: '__defineGetter__', message: 'Please use Object.defineProperty instead.'}, {property: '__defineSetter__', message: 'Please use Object.defineProperty instead.'}, {object: 'Math', property: 'pow', message: 'Use the exponentiation operator (**) instead.'}],
      'no-return-assign': ['error', 'always'],
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-tabs': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-unreachable-loop': ['error', {ignore: []}],
      'no-unused-expressions': ['error', {allowShortCircuit: false, allowTernary: false, allowTaggedTemplates: false, enforceForJSX: false}],
      'no-use-before-define': ['error', {functions: true, classes: true, variables: true}],
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': ['error', {ignoreDestructuring: false, ignoreImport: false, ignoreExport: false}],
      'no-useless-return': 'error',
      'no-void': 'error',
      'nonblock-statement-body-position': ['error', 'beside', {overrides: {}}],
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': ['error', {allowAllPropertiesOnSameLine: true, allowMultiplePropertiesPerLine: false}],
      'one-var-declaration-per-line': ['error', 'always'],
      'operator-linebreak': ['error', 'before', {overrides: {'=': 'none'}}],
      'padded-blocks': ['error', {blocks: 'never', classes: 'never', switches: 'never'}, {allowSingleLineBlocks: true}],
      'prefer-exponentiation-operator': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
      'prefer-regex-literals': ['error', {disallowRedundantWrapping: true}],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'quote-props': ['error', 'as-needed', {keywords: false, unnecessary: true, numbers: false}],
      'radix': 'error',
      'react/button-has-type': ['error', {button: true, submit: true, reset: false}],
      'react/default-props-match-prop-types': ['error', {allowRequiredDefaults: false}],
      'react/destructuring-assignment': ['error', 'always'],
      'react/function-component-definition': ['error', {namedComponents: ['function-declaration', 'function-expression'], unnamedComponents: 'function-expression'}],
      'react/jsx-boolean-value': ['error', 'never', {always: []}],
      'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
      'react/jsx-closing-tag-location': 'error',
      'react/jsx-curly-brace-presence': ['error', {props: 'never', children: 'never'}],
      'react/jsx-curly-newline': ['error', {multiline: 'consistent', singleline: 'consistent'}],
      'react/jsx-curly-spacing': ['error', 'never', {allowMultiline: true}],
      'react/jsx-equals-spacing': ['error', 'never'],
      'react/jsx-first-prop-new-line': ['error', 'multiline-multiprop'],
      'react/jsx-fragments': ['error', 'syntax'],
      'react/jsx-max-props-per-line': ['error', {maximum: 1, when: 'multiline'}],
      'react/jsx-no-bind': ['error', {ignoreRefs: true, allowArrowFunctions: true, allowFunctions: false, allowBind: false, ignoreDOMComponents: true}],
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-no-script-url': ['error', [{name: 'Link', props: ['to']}]],
      'react/jsx-no-useless-fragment': 'error',
      'react/jsx-one-expression-per-line': ['error', {allow: 'single-child'}],
      'react/jsx-pascal-case': ['error', {allowAllCaps: true, ignore: []}],
      'react/jsx-props-no-multi-spaces': 'error',
      'react/jsx-tag-spacing': ['error', {closingSlash: 'never', beforeSelfClosing: 'always', afterOpening: 'never', beforeClosing: 'never'}],
      'react/jsx-wrap-multilines': ['error', {declaration: 'parens-new-line', assignment: 'parens-new-line', return: 'parens-new-line', arrow: 'parens-new-line', condition: 'parens-new-line', logical: 'parens-new-line', prop: 'parens-new-line'}],
      'react/no-access-state-in-setstate': 'error',
      'react/no-array-index-key': 'error',
      'react/no-arrow-function-lifecycle': 'error',
      'react/no-invalid-html-attribute': 'error',
      'react/no-namespace': 'error',
      'react/no-this-in-sfc': 'error',
      'react/no-unstable-nested-components': 'error',
      'react/no-unused-class-component-methods': 'error',
      'react/no-unused-prop-types': ['error', {customValidators: [], skipShapeProps: true}],
      'react/no-unused-state': 'error',
      'react/prefer-exact-props': 'error',
      'react/self-closing-comp': 'error',
      'react/sort-comp': ['error', {order: ['static-variables', 'static-methods', 'instance-variables', 'lifecycle', '/^handle.+$/', '/^on.+$/', 'getters', 'setters', '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/', 'instance-methods', 'everything-else', 'rendering'], groups: {lifecycle: ['displayName', 'propTypes', 'contextTypes', 'childContextTypes', 'mixins', 'statics', 'defaultProps', 'constructor', 'getDefaultProps', 'getInitialState', 'state', 'getChildContext', 'getDerivedStateFromProps', 'componentWillMount', 'UNSAFE_componentWillMount', 'componentDidMount', 'componentWillReceiveProps', 'UNSAFE_componentWillReceiveProps', 'shouldComponentUpdate', 'componentWillUpdate', 'UNSAFE_componentWillUpdate', 'getSnapshotBeforeUpdate', 'componentDidUpdate', 'componentDidCatch', 'componentWillUnmount'], rendering: ['/^render.+$/', 'render']}}],
      'react/state-in-constructor': ['error', 'always'],
      'react/static-property-placement': ['error', 'property assignment'],
      'react/style-prop-object': 'error',
      'react/void-dom-elements-no-children': 'error',
      'rest-spread-spacing': ['error', 'never'],
      'semi-spacing': ['error', {before: false, after: true}],
      'semi-style': ['error', 'last'],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', {words: true, nonwords: false, overrides: {}}],
      'strict': ['error', 'never'],
      'switch-colon-spacing': ['error', {after: true, before: false}],
      'symbol-description': 'error',
      'template-tag-spacing': ['error', 'never'],
      'unicode-bom': ['error', 'never'],
      'vars-on-top': 'error',
      'wrap-iife': ['error', 'outside', {functionPrototypeMethods: false}],
      'yield-star-spacing': ['error', 'after'],
      'yoda': 'error',

      // === Existing project-specific rules ===
      '@typescript-eslint/no-explicit-any': 'off',
      'react/jsx-filename-extension': ['warn', {extensions: ['.jsx', '.js', '.tsx', '.ts']}],
      'react/require-default-props': 'off',
      'react/jsx-props-no-spreading': 'off',
      indent: ['error', 4, {SwitchCase: 1}],
      'react/jsx-indent': ['error', 4],
      'react/jsx-indent-props': ['error', 4],
      'import/extensions': ['error', 'ignorePackages', {js: 'never', jsx: 'never', ts: 'never', tsx: 'never'}],
      'object-curly-newline': ['error', {
        ObjectExpression: {minProperties: 4, multiline: true, consistent: true},
        ObjectPattern: {minProperties: 4, multiline: true, consistent: true},
        ImportDeclaration: {minProperties: 0, consistent: true},
        ExportDeclaration: {minProperties: 4, multiline: true, consistent: true},
      }],

      // === Additional stylistic rules ===
      semi: ['error', 'always'],
      'comma-dangle': ['error', 'always-multiline'],
      'prefer-destructuring': ['error', {object: true, array: true}],
      'no-param-reassign': ['error', {props: false}],
      'no-underscore-dangle': 'error',
      'func-names': ['error', 'as-needed'],
      'arrow-body-style': ['error', 'as-needed'],
      'prefer-arrow-callback': 'error',
      'arrow-parens': ['error', 'always'],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-multiple-empty-lines': ['error', {max: 1}],
      'eol-last': ['error', 'always'],
      quotes: ['error', 'single', {avoidEscape: true}],
      'jsx-quotes': ['error', 'prefer-double'],
      'no-console': 'warn',
      'no-alert': 'warn',
      'object-shorthand': ['error', 'always'],
      'prefer-template': 'error',
      'template-curly-spacing': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'brace-style': ['error', '1tbs', {allowSingleLine: true}],
      'keyword-spacing': ['error', {before: true, after: true}],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', {anonymous: 'always', named: 'never', asyncArrow: 'always'}],
      'spaced-comment': ['error', 'always'],
      'no-trailing-spaces': 'error',
      'no-multi-spaces': 'error',
      'block-spacing': ['error', 'always'],
      'comma-spacing': ['error', {before: false, after: true}],
      'key-spacing': ['error', {beforeColon: false, afterColon: true}],
      'prefer-object-spread': 'error',
      'no-plusplus': ['error', {allowForLoopAfterthoughts: true}],
      'no-unneeded-ternary': 'error',
      'one-var': ['error', 'never'],
      'operator-assignment': ['error', 'always'],
      'no-else-return': ['error', {allowElseIf: false}],
      eqeqeq: ['error', 'always'],
      'no-restricted-syntax': ['error', 'ForInStatement', 'ForOfStatement', 'LabeledStatement', 'WithStatement'],
    },
  },
  { ignores: ['node_modules', 'build', 'public', '**/*.test.*', '**/__tests__/**'] },
];
